#!/usr/bin/env python
# -*- coding: utf-8 -*-

allCountries = [{"flag":"https://restcountries.eu/data/afg.svg","name":"Afghanistan","capital":"Kabul","region":"Asia"},
{"flag":"https://restcountries.eu/data/ala.svg","name":"Åland Islands","capital":"Mariehamn","region":"Europe"},
{"flag":"https://restcountries.eu/data/alb.svg","name":"Albania","capital":"Tirana","region":"Europe"},
{"flag":"https://restcountries.eu/data/dza.svg","name":"Algeria","capital":"Algiers","region":"Africa"},
{"flag":"https://restcountries.eu/data/asm.svg","name":"American Samoa","capital":"Pago Pago","region":"Oceania"},
{"flag":"https://restcountries.eu/data/and.svg","name":"Andorra","capital":"Andorra la Vella","region":"Europe"},
{"flag":"https://restcountries.eu/data/ago.svg","name":"Angola","capital":"Luanda","region":"Africa"},
{"flag":"https://restcountries.eu/data/aia.svg","name":"Anguilla","capital":"The Valley","region":"Americas"},
{"flag":"https://restcountries.eu/data/ata.svg","name":"Antarctica","capital":"","region":"Polar"},
{"flag":"https://restcountries.eu/data/atg.svg","name":"Antigua and Barbuda","capital":"Saint John's","region":"Americas"},
{"flag":"https://restcountries.eu/data/arg.svg","name":"Argentina","capital":"Buenos Aires","region":"Americas"},
{"flag":"https://restcountries.eu/data/arm.svg","name":"Armenia","capital":"Yerevan","region":"Asia"},
{"flag":"https://restcountries.eu/data/abw.svg","name":"Aruba","capital":"Oranjestad","region":"Americas"},
{"flag":"https://restcountries.eu/data/aus.svg","name":"Australia","capital":"Canberra","region":"Oceania"},
{"flag":"https://restcountries.eu/data/aut.svg","name":"Austria","capital":"Vienna","region":"Europe"},
{"flag":"https://restcountries.eu/data/aze.svg","name":"Azerbaijan","capital":"Baku","region":"Asia"},
{"flag":"https://restcountries.eu/data/bhs.svg","name":"Bahamas","capital":"Nassau","region":"Americas"},
{"flag":"https://restcountries.eu/data/bhr.svg","name":"Bahrain","capital":"Manama","region":"Asia"},
{"flag":"https://restcountries.eu/data/bgd.svg","name":"Bangladesh","capital":"Dhaka","region":"Asia"},
{"flag":"https://restcountries.eu/data/brb.svg","name":"Barbados","capital":"Bridgetown","region":"Americas"},
{"flag":"https://restcountries.eu/data/blr.svg","name":"Belarus","capital":"Minsk","region":"Europe"},
{"flag":"https://restcountries.eu/data/bel.svg","name":"Belgium","capital":"Brussels","region":"Europe"},
{"flag":"https://restcountries.eu/data/blz.svg","name":"Belize","capital":"Belmopan","region":"Americas"},
{"flag":"https://restcountries.eu/data/ben.svg","name":"Benin","capital":"Porto-Novo","region":"Africa"},
{"flag":"https://restcountries.eu/data/bmu.svg","name":"Bermuda","capital":"Hamilton","region":"Americas"},
{"flag":"https://restcountries.eu/data/btn.svg","name":"Bhutan","capital":"Thimphu","region":"Asia"},
{"flag":"https://restcountries.eu/data/bol.svg","name":"Bolivia (Plurinational State of)","capital":"Sucre","region":"Americas"},
{"flag":"https://restcountries.eu/data/bes.svg","name":"Bonaire, Sint Eustatius and Saba","capital":"Kralendijk","region":"Americas"},
{"flag":"https://restcountries.eu/data/bih.svg","name":"Bosnia and Herzegovina","capital":"Sarajevo","region":"Europe"},
{"flag":"https://restcountries.eu/data/bwa.svg","name":"Botswana","capital":"Gaborone","region":"Africa"},
{"flag":"https://restcountries.eu/data/bvt.svg","name":"Bouvet Island","capital":"","region":""},
{"flag":"https://restcountries.eu/data/bra.svg","name":"Brazil","capital":"Brasília","region":"Americas"},
{"flag":"https://restcountries.eu/data/iot.svg","name":"British Indian Ocean Territory","capital":"Diego Garcia","region":"Africa"},
{"flag":"https://restcountries.eu/data/umi.svg","name":"United States Minor Outlying Islands","capital":"","region":"Americas"},
{"flag":"https://restcountries.eu/data/vgb.svg","name":"Virgin Islands (British)","capital":"Road Town","region":"Americas"},
{"flag":"https://restcountries.eu/data/vir.svg","name":"Virgin Islands (U.S.)","capital":"Charlotte Amalie","region":"Americas"},
{"flag":"https://restcountries.eu/data/brn.svg","name":"Brunei Darussalam","capital":"Bandar Seri Begawan","region":"Asia"},
{"flag":"https://restcountries.eu/data/bgr.svg","name":"Bulgaria","capital":"Sofia","region":"Europe"},
{"flag":"https://restcountries.eu/data/bfa.svg","name":"Burkina Faso","capital":"Ouagadougou","region":"Africa"},
{"flag":"https://restcountries.eu/data/bdi.svg","name":"Burundi","capital":"Bujumbura","region":"Africa"},
{"flag":"https://restcountries.eu/data/khm.svg","name":"Cambodia","capital":"Phnom Penh","region":"Asia"},
{"flag":"https://restcountries.eu/data/cmr.svg","name":"Cameroon","capital":"Yaoundé","region":"Africa"},
{"flag":"https://restcountries.eu/data/can.svg","name":"Canada","capital":"Ottawa","region":"Americas"},
{"flag":"https://restcountries.eu/data/cpv.svg","name":"Cabo Verde","capital":"Praia","region":"Africa"},
{"flag":"https://restcountries.eu/data/cym.svg","name":"Cayman Islands","capital":"George Town","region":"Americas"},
{"flag":"https://restcountries.eu/data/caf.svg","name":"Central African Republic","capital":"Bangui","region":"Africa"},
{"flag":"https://restcountries.eu/data/tcd.svg","name":"Chad","capital":"N'Djamena","region":"Africa"},
{"flag":"https://restcountries.eu/data/chl.svg","name":"Chile","capital":"Santiago","region":"Americas"},
{"flag":"https://restcountries.eu/data/chn.svg","name":"China","capital":"Beijing","region":"Asia"},
{"flag":"https://restcountries.eu/data/cxr.svg","name":"Christmas Island","capital":"Flying Fish Cove","region":"Oceania"},
{"flag":"https://restcountries.eu/data/cck.svg","name":"Cocos (Keeling) Islands","capital":"West Island","region":"Oceania"},
{"flag":"https://restcountries.eu/data/col.svg","name":"Colombia","capital":"Bogotá","region":"Americas"},
{"flag":"https://restcountries.eu/data/com.svg","name":"Comoros","capital":"Moroni","region":"Africa"},
{"flag":"https://restcountries.eu/data/cog.svg","name":"Congo","capital":"Brazzaville","region":"Africa"},
{"flag":"https://restcountries.eu/data/cod.svg","name":"Congo (Democratic Republic of the)","capital":"Kinshasa","region":"Africa"},
{"flag":"https://restcountries.eu/data/cok.svg","name":"Cook Islands","capital":"Avarua","region":"Oceania"},
{"flag":"https://restcountries.eu/data/cri.svg","name":"Costa Rica","capital":"San José","region":"Americas"},
{"flag":"https://restcountries.eu/data/hrv.svg","name":"Croatia","capital":"Zagreb","region":"Europe"},
{"flag":"https://restcountries.eu/data/cub.svg","name":"Cuba","capital":"Havana","region":"Americas"},
{"flag":"https://restcountries.eu/data/cuw.svg","name":"Curaçao","capital":"Willemstad","region":"Americas"},
{"flag":"https://restcountries.eu/data/cyp.svg","name":"Cyprus","capital":"Nicosia","region":"Europe"},
{"flag":"https://restcountries.eu/data/cze.svg","name":"Czech Republic","capital":"Prague","region":"Europe"},
{"flag":"https://restcountries.eu/data/dnk.svg","name":"Denmark","capital":"Copenhagen","region":"Europe"},
{"flag":"https://restcountries.eu/data/dji.svg","name":"Djibouti","capital":"Djibouti","region":"Africa"},
{"flag":"https://restcountries.eu/data/dma.svg","name":"Dominica","capital":"Roseau","region":"Americas"},
{"flag":"https://restcountries.eu/data/dom.svg","name":"Dominican Republic","capital":"Santo Domingo","region":"Americas"},
{"flag":"https://restcountries.eu/data/ecu.svg","name":"Ecuador","capital":"Quito","region":"Americas"},
{"flag":"https://restcountries.eu/data/egy.svg","name":"Egypt","capital":"Cairo","region":"Africa"},
{"flag":"https://restcountries.eu/data/slv.svg","name":"El Salvador","capital":"San Salvador","region":"Americas"},
{"flag":"https://restcountries.eu/data/gnq.svg","name":"Equatorial Guinea","capital":"Malabo","region":"Africa"},
{"flag":"https://restcountries.eu/data/eri.svg","name":"Eritrea","capital":"Asmara","region":"Africa"},
{"flag":"https://restcountries.eu/data/est.svg","name":"Estonia","capital":"Tallinn","region":"Europe"},
{"flag":"https://restcountries.eu/data/eth.svg","name":"Ethiopia","capital":"Addis Ababa","region":"Africa"},
{"flag":"https://restcountries.eu/data/flk.svg","name":"Falkland Islands (Malvinas)","capital":"Stanley","region":"Americas"},
{"flag":"https://restcountries.eu/data/fro.svg","name":"Faroe Islands","capital":"Tórshavn","region":"Europe"},
{"flag":"https://restcountries.eu/data/fji.svg","name":"Fiji","capital":"Suva","region":"Oceania"},
{"flag":"https://restcountries.eu/data/fin.svg","name":"Finland","capital":"Helsinki","region":"Europe"},
{"flag":"https://restcountries.eu/data/fra.svg","name":"France","capital":"Paris","region":"Europe"},
{"flag":"https://restcountries.eu/data/guf.svg","name":"French Guiana","capital":"Cayenne","region":"Americas"},
{"flag":"https://restcountries.eu/data/pyf.svg","name":"French Polynesia","capital":"Papeetē","region":"Oceania"},
{"flag":"https://restcountries.eu/data/atf.svg","name":"French Southern Territories","capital":"Port-aux-Français","region":"Africa"},
{"flag":"https://restcountries.eu/data/gab.svg","name":"Gabon","capital":"Libreville","region":"Africa"},
{"flag":"https://restcountries.eu/data/gmb.svg","name":"Gambia","capital":"Banjul","region":"Africa"},
{"flag":"https://restcountries.eu/data/geo.svg","name":"Georgia","capital":"Tbilisi","region":"Asia"},
{"flag":"https://restcountries.eu/data/deu.svg","name":"Germany","capital":"Berlin","region":"Europe"},
{"flag":"https://restcountries.eu/data/gha.svg","name":"Ghana","capital":"Accra","region":"Africa"},
{"flag":"https://restcountries.eu/data/gib.svg","name":"Gibraltar","capital":"Gibraltar","region":"Europe"},
{"flag":"https://restcountries.eu/data/grc.svg","name":"Greece","capital":"Athens","region":"Europe"},
{"flag":"https://restcountries.eu/data/grl.svg","name":"Greenland","capital":"Nuuk","region":"Americas"},
{"flag":"https://restcountries.eu/data/grd.svg","name":"Grenada","capital":"St. George's","region":"Americas"},
{"flag":"https://restcountries.eu/data/glp.svg","name":"Guadeloupe","capital":"Basse-Terre","region":"Americas"},
{"flag":"https://restcountries.eu/data/gum.svg","name":"Guam","capital":"Hagåtña","region":"Oceania"},
{"flag":"https://restcountries.eu/data/gtm.svg","name":"Guatemala","capital":"Guatemala City","region":"Americas"},
{"flag":"https://restcountries.eu/data/ggy.svg","name":"Guernsey","capital":"St. Peter Port","region":"Europe"},
{"flag":"https://restcountries.eu/data/gin.svg","name":"Guinea","capital":"Conakry","region":"Africa"},
{"flag":"https://restcountries.eu/data/gnb.svg","name":"Guinea-Bissau","capital":"Bissau","region":"Africa"},
{"flag":"https://restcountries.eu/data/guy.svg","name":"Guyana","capital":"Georgetown","region":"Americas"},
{"flag":"https://restcountries.eu/data/hti.svg","name":"Haiti","capital":"Port-au-Prince","region":"Americas"},
{"flag":"https://restcountries.eu/data/hmd.svg","name":"Heard Island and McDonald Islands","capital":"","region":""},
{"flag":"https://restcountries.eu/data/vat.svg","name":"Holy See","capital":"Rome","region":"Europe"},
{"flag":"https://restcountries.eu/data/hnd.svg","name":"Honduras","capital":"Tegucigalpa","region":"Americas"},
{"flag":"https://restcountries.eu/data/hkg.svg","name":"Hong Kong","capital":"City of Victoria","region":"Asia"},
{"flag":"https://restcountries.eu/data/hun.svg","name":"Hungary","capital":"Budapest","region":"Europe"},
{"flag":"https://restcountries.eu/data/isl.svg","name":"Iceland","capital":"Reykjavík","region":"Europe"},
{"flag":"https://restcountries.eu/data/ind.svg","name":"India","capital":"New Delhi","region":"Asia"},
{"flag":"https://restcountries.eu/data/idn.svg","name":"Indonesia","capital":"Jakarta","region":"Asia"},
{"flag":"https://restcountries.eu/data/civ.svg","name":"Côte d'Ivoire","capital":"Yamoussoukro","region":"Africa"},
{"flag":"https://restcountries.eu/data/irn.svg","name":"Iran (Islamic Republic of)","capital":"Tehran","region":"Asia"},
{"flag":"https://restcountries.eu/data/irq.svg","name":"Iraq","capital":"Baghdad","region":"Asia"},
{"flag":"https://restcountries.eu/data/irl.svg","name":"Ireland","capital":"Dublin","region":"Europe"},
{"flag":"https://restcountries.eu/data/imn.svg","name":"Isle of Man","capital":"Douglas","region":"Europe"},
{"flag":"https://restcountries.eu/data/isr.svg","name":"Israel","capital":"Jerusalem","region":"Asia"},
{"flag":"https://restcountries.eu/data/ita.svg","name":"Italy","capital":"Rome","region":"Europe"},
{"flag":"https://restcountries.eu/data/jam.svg","name":"Jamaica","capital":"Kingston","region":"Americas"},
{"flag":"https://restcountries.eu/data/jpn.svg","name":"Japan","capital":"Tokyo","region":"Asia"},
{"flag":"https://restcountries.eu/data/jey.svg","name":"Jersey","capital":"Saint Helier","region":"Europe"},
{"flag":"https://restcountries.eu/data/jor.svg","name":"Jordan","capital":"Amman","region":"Asia"},
{"flag":"https://restcountries.eu/data/kaz.svg","name":"Kazakhstan","capital":"Astana","region":"Asia"},
{"flag":"https://restcountries.eu/data/ken.svg","name":"Kenya","capital":"Nairobi","region":"Africa"},
{"flag":"https://restcountries.eu/data/kir.svg","name":"Kiribati","capital":"South Tarawa","region":"Oceania"},
{"flag":"https://restcountries.eu/data/kwt.svg","name":"Kuwait","capital":"Kuwait City","region":"Asia"},
{"flag":"https://restcountries.eu/data/kgz.svg","name":"Kyrgyzstan","capital":"Bishkek","region":"Asia"},
{"flag":"https://restcountries.eu/data/lao.svg","name":"Lao People's Democratic Republic","capital":"Vientiane","region":"Asia"},
{"flag":"https://restcountries.eu/data/lva.svg","name":"Latvia","capital":"Riga","region":"Europe"},
{"flag":"https://restcountries.eu/data/lbn.svg","name":"Lebanon","capital":"Beirut","region":"Asia"},
{"flag":"https://restcountries.eu/data/lso.svg","name":"Lesotho","capital":"Maseru","region":"Africa"},
{"flag":"https://restcountries.eu/data/lbr.svg","name":"Liberia","capital":"Monrovia","region":"Africa"},
{"flag":"https://restcountries.eu/data/lby.svg","name":"Libya","capital":"Tripoli","region":"Africa"},
{"flag":"https://restcountries.eu/data/lie.svg","name":"Liechtenstein","capital":"Vaduz","region":"Europe"},
{"flag":"https://restcountries.eu/data/ltu.svg","name":"Lithuania","capital":"Vilnius","region":"Europe"},
{"flag":"https://restcountries.eu/data/lux.svg","name":"Luxembourg","capital":"Luxembourg","region":"Europe"},
{"flag":"https://restcountries.eu/data/mac.svg","name":"Macao","capital":"","region":"Asia"},
{"flag":"https://restcountries.eu/data/mkd.svg","name":"Macedonia (the former Yugoslav Republic of)","capital":"Skopje","region":"Europe"},
{"flag":"https://restcountries.eu/data/mdg.svg","name":"Madagascar","capital":"Antananarivo","region":"Africa"},
{"flag":"https://restcountries.eu/data/mwi.svg","name":"Malawi","capital":"Lilongwe","region":"Africa"},
{"flag":"https://restcountries.eu/data/mys.svg","name":"Malaysia","capital":"Kuala Lumpur","region":"Asia"},
{"flag":"https://restcountries.eu/data/mdv.svg","name":"Maldives","capital":"Malé","region":"Asia"},
{"flag":"https://restcountries.eu/data/mli.svg","name":"Mali","capital":"Bamako","region":"Africa"},
{"flag":"https://restcountries.eu/data/mlt.svg","name":"Malta","capital":"Valletta","region":"Europe"},
{"flag":"https://restcountries.eu/data/mhl.svg","name":"Marshall Islands","capital":"Majuro","region":"Oceania"},
{"flag":"https://restcountries.eu/data/mtq.svg","name":"Martinique","capital":"Fort-de-France","region":"Americas"},
{"flag":"https://restcountries.eu/data/mrt.svg","name":"Mauritania","capital":"Nouakchott","region":"Africa"},
{"flag":"https://restcountries.eu/data/mus.svg","name":"Mauritius","capital":"Port Louis","region":"Africa"},
{"flag":"https://restcountries.eu/data/myt.svg","name":"Mayotte","capital":"Mamoudzou","region":"Africa"},
{"flag":"https://restcountries.eu/data/mex.svg","name":"Mexico","capital":"Mexico City","region":"Americas"},
{"flag":"https://restcountries.eu/data/fsm.svg","name":"Micronesia (Federated States of)","capital":"Palikir","region":"Oceania"},
{"flag":"https://restcountries.eu/data/mda.svg","name":"Moldova (Republic of)","capital":"Chișinău","region":"Europe"},
{"flag":"https://restcountries.eu/data/mco.svg","name":"Monaco","capital":"Monaco","region":"Europe"},
{"flag":"https://restcountries.eu/data/mng.svg","name":"Mongolia","capital":"Ulan Bator","region":"Asia"},
{"flag":"https://restcountries.eu/data/mne.svg","name":"Montenegro","capital":"Podgorica","region":"Europe"},
{"flag":"https://restcountries.eu/data/msr.svg","name":"Montserrat","capital":"Plymouth","region":"Americas"},
{"flag":"https://restcountries.eu/data/mar.svg","name":"Morocco","capital":"Rabat","region":"Africa"},
{"flag":"https://restcountries.eu/data/moz.svg","name":"Mozambique","capital":"Maputo","region":"Africa"},
{"flag":"https://restcountries.eu/data/mmr.svg","name":"Myanmar","capital":"Naypyidaw","region":"Asia"},
{"flag":"https://restcountries.eu/data/nam.svg","name":"Namibia","capital":"Windhoek","region":"Africa"},
{"flag":"https://restcountries.eu/data/nru.svg","name":"Nauru","capital":"Yaren","region":"Oceania"},
{"flag":"https://restcountries.eu/data/npl.svg","name":"Nepal","capital":"Kathmandu","region":"Asia"},
{"flag":"https://restcountries.eu/data/nld.svg","name":"Netherlands","capital":"Amsterdam","region":"Europe"},
{"flag":"https://restcountries.eu/data/ncl.svg","name":"New Caledonia","capital":"Nouméa","region":"Oceania"},
{"flag":"https://restcountries.eu/data/nzl.svg","name":"New Zealand","capital":"Wellington","region":"Oceania"},
{"flag":"https://restcountries.eu/data/nic.svg","name":"Nicaragua","capital":"Managua","region":"Americas"},
{"flag":"https://restcountries.eu/data/ner.svg","name":"Niger","capital":"Niamey","region":"Africa"},
{"flag":"https://restcountries.eu/data/nga.svg","name":"Nigeria","capital":"Abuja","region":"Africa"},
{"flag":"https://restcountries.eu/data/niu.svg","name":"Niue","capital":"Alofi","region":"Oceania"},
{"flag":"https://restcountries.eu/data/nfk.svg","name":"Norfolk Island","capital":"Kingston","region":"Oceania"},
{"flag":"https://restcountries.eu/data/prk.svg","name":"Korea (Democratic People's Republic of)","capital":"Pyongyang","region":"Asia"},
{"flag":"https://restcountries.eu/data/mnp.svg","name":"Northern Mariana Islands","capital":"Saipan","region":"Oceania"},
{"flag":"https://restcountries.eu/data/nor.svg","name":"Norway","capital":"Oslo","region":"Europe"},
{"flag":"https://restcountries.eu/data/omn.svg","name":"Oman","capital":"Muscat","region":"Asia"},
{"flag":"https://restcountries.eu/data/pak.svg","name":"Pakistan","capital":"Islamabad","region":"Asia"},
{"flag":"https://restcountries.eu/data/plw.svg","name":"Palau","capital":"Ngerulmud","region":"Oceania"},
{"flag":"https://restcountries.eu/data/pse.svg","name":"Palestine, State of","capital":"Ramallah","region":"Asia"},
{"flag":"https://restcountries.eu/data/pan.svg","name":"Panama","capital":"Panama City","region":"Americas"},
{"flag":"https://restcountries.eu/data/png.svg","name":"Papua New Guinea","capital":"Port Moresby","region":"Oceania"},
{"flag":"https://restcountries.eu/data/pry.svg","name":"Paraguay","capital":"Asunción","region":"Americas"},
{"flag":"https://restcountries.eu/data/per.svg","name":"Peru","capital":"Lima","region":"Americas"},
{"flag":"https://restcountries.eu/data/phl.svg","name":"Philippines","capital":"Manila","region":"Asia"},
{"flag":"https://restcountries.eu/data/pcn.svg","name":"Pitcairn","capital":"Adamstown","region":"Oceania"},
{"flag":"https://restcountries.eu/data/pol.svg","name":"Poland","capital":"Warsaw","region":"Europe"},
{"flag":"https://restcountries.eu/data/prt.svg","name":"Portugal","capital":"Lisbon","region":"Europe"},
{"flag":"https://restcountries.eu/data/pri.svg","name":"Puerto Rico","capital":"San Juan","region":"Americas"},
{"flag":"https://restcountries.eu/data/qat.svg","name":"Qatar","capital":"Doha","region":"Asia"},
{"flag":"https://restcountries.eu/data/kos.svg","name":"Republic of Kosovo","capital":"Pristina","region":"Europe"},
{"flag":"https://restcountries.eu/data/reu.svg","name":"Réunion","capital":"Saint-Denis","region":"Africa"},
{"flag":"https://restcountries.eu/data/rou.svg","name":"Romania","capital":"Bucharest","region":"Europe"},
{"flag":"https://restcountries.eu/data/rus.svg","name":"Russian Federation","capital":"Moscow","region":"Europe"},
{"flag":"https://restcountries.eu/data/rwa.svg","name":"Rwanda","capital":"Kigali","region":"Africa"},
{"flag":"https://restcountries.eu/data/blm.svg","name":"Saint Barthélemy","capital":"Gustavia","region":"Americas"},
{"flag":"https://restcountries.eu/data/shn.svg","name":"Saint Helena, Ascension and Tristan da Cunha","capital":"Jamestown","region":"Africa"},
{"flag":"https://restcountries.eu/data/kna.svg","name":"Saint Kitts and Nevis","capital":"Basseterre","region":"Americas"},
{"flag":"https://restcountries.eu/data/lca.svg","name":"Saint Lucia","capital":"Castries","region":"Americas"},
{"flag":"https://restcountries.eu/data/maf.svg","name":"Saint Martin (French part)","capital":"Marigot","region":"Americas"},
{"flag":"https://restcountries.eu/data/spm.svg","name":"Saint Pierre and Miquelon","capital":"Saint-Pierre","region":"Americas"},
{"flag":"https://restcountries.eu/data/vct.svg","name":"Saint Vincent and the Grenadines","capital":"Kingstown","region":"Americas"},
{"flag":"https://restcountries.eu/data/wsm.svg","name":"Samoa","capital":"Apia","region":"Oceania"},
{"flag":"https://restcountries.eu/data/smr.svg","name":"San Marino","capital":"City of San Marino","region":"Europe"},
{"flag":"https://restcountries.eu/data/stp.svg","name":"Sao Tome and Principe","capital":"São Tomé","region":"Africa"},
{"flag":"https://restcountries.eu/data/sau.svg","name":"Saudi Arabia","capital":"Riyadh","region":"Asia"},
{"flag":"https://restcountries.eu/data/sen.svg","name":"Senegal","capital":"Dakar","region":"Africa"},
{"flag":"https://restcountries.eu/data/srb.svg","name":"Serbia","capital":"Belgrade","region":"Europe"},
{"flag":"https://restcountries.eu/data/syc.svg","name":"Seychelles","capital":"Victoria","region":"Africa"},
{"flag":"https://restcountries.eu/data/sle.svg","name":"Sierra Leone","capital":"Freetown","region":"Africa"},
{"flag":"https://restcountries.eu/data/sgp.svg","name":"Singapore","capital":"Singapore","region":"Asia"},
{"flag":"https://restcountries.eu/data/sxm.svg","name":"Sint Maarten (Dutch part)","capital":"Philipsburg","region":"Americas"},
{"flag":"https://restcountries.eu/data/svk.svg","name":"Slovakia","capital":"Bratislava","region":"Europe"},
{"flag":"https://restcountries.eu/data/svn.svg","name":"Slovenia","capital":"Ljubljana","region":"Europe"},
{"flag":"https://restcountries.eu/data/slb.svg","name":"Solomon Islands","capital":"Honiara","region":"Oceania"},
{"flag":"https://restcountries.eu/data/som.svg","name":"Somalia","capital":"Mogadishu","region":"Africa"},
{"flag":"https://restcountries.eu/data/zaf.svg","name":"South Africa","capital":"Pretoria","region":"Africa"},
{"flag":"https://restcountries.eu/data/sgs.svg","name":"South Georgia and the South Sandwich Islands","capital":"King Edward Point","region":"Americas"},
{"flag":"https://restcountries.eu/data/kor.svg","name":"Korea (Republic of)","capital":"Seoul","region":"Asia"},
{"flag":"https://restcountries.eu/data/ssd.svg","name":"South Sudan","capital":"Juba","region":"Africa"},
{"flag":"https://restcountries.eu/data/esp.svg","name":"Spain","capital":"Madrid","region":"Europe"},
{"flag":"https://restcountries.eu/data/lka.svg","name":"Sri Lanka","capital":"Colombo","region":"Asia"},
{"flag":"https://restcountries.eu/data/sdn.svg","name":"Sudan","capital":"Khartoum","region":"Africa"},
{"flag":"https://restcountries.eu/data/sur.svg","name":"Suriname","capital":"Paramaribo","region":"Americas"},
{"flag":"https://restcountries.eu/data/sjm.svg","name":"Svalbard and Jan Mayen","capital":"Longyearbyen","region":"Europe"},
{"flag":"https://restcountries.eu/data/swz.svg","name":"Swaziland","capital":"Lobamba","region":"Africa"},
{"flag":"https://restcountries.eu/data/swe.svg","name":"Sweden","capital":"Stockholm","region":"Europe"},
{"flag":"https://restcountries.eu/data/che.svg","name":"Switzerland","capital":"Bern","region":"Europe"},
{"flag":"https://restcountries.eu/data/syr.svg","name":"Syrian Arab Republic","capital":"Damascus","region":"Asia"},
{"flag":"https://restcountries.eu/data/twn.svg","name":"Taiwan","capital":"Taipei","region":"Asia"},
{"flag":"https://restcountries.eu/data/tjk.svg","name":"Tajikistan","capital":"Dushanbe","region":"Asia"},
{"flag":"https://restcountries.eu/data/tza.svg","name":"Tanzania, United Republic of","capital":"Dodoma","region":"Africa"},
{"flag":"https://restcountries.eu/data/tha.svg","name":"Thailand","capital":"Bangkok","region":"Asia"},
{"flag":"https://restcountries.eu/data/tls.svg","name":"Timor-Leste","capital":"Dili","region":"Asia"},
{"flag":"https://restcountries.eu/data/tgo.svg","name":"Togo","capital":"Lomé","region":"Africa"},
{"flag":"https://restcountries.eu/data/tkl.svg","name":"Tokelau","capital":"Fakaofo","region":"Oceania"},
{"flag":"https://restcountries.eu/data/ton.svg","name":"Tonga","capital":"Nuku'alofa","region":"Oceania"},
{"flag":"https://restcountries.eu/data/tto.svg","name":"Trinidad and Tobago","capital":"Port of Spain","region":"Americas"},
{"flag":"https://restcountries.eu/data/tun.svg","name":"Tunisia","capital":"Tunis","region":"Africa"},
{"flag":"https://restcountries.eu/data/tur.svg","name":"Turkey","capital":"Ankara","region":"Asia"},
{"flag":"https://restcountries.eu/data/tkm.svg","name":"Turkmenistan","capital":"Ashgabat","region":"Asia"},
{"flag":"https://restcountries.eu/data/tca.svg","name":"Turks and Caicos Islands","capital":"Cockburn Town","region":"Americas"},
{"flag":"https://restcountries.eu/data/tuv.svg","name":"Tuvalu","capital":"Funafuti","region":"Oceania"},
{"flag":"https://restcountries.eu/data/uga.svg","name":"Uganda","capital":"Kampala","region":"Africa"},
{"flag":"https://restcountries.eu/data/ukr.svg","name":"Ukraine","capital":"Kiev","region":"Europe"},
{"flag":"https://restcountries.eu/data/are.svg","name":"United Arab Emirates","capital":"Abu Dhabi","region":"Asia"},
{"flag":"https://restcountries.eu/data/gbr.svg","name":"United Kingdom of Great Britain and Northern Ireland","capital":"London","region":"Europe"},
{"flag":"https://restcountries.eu/data/usa.svg","name":"United States of America","capital":"Washington, D.C.","region":"Americas"},
{"flag":"https://restcountries.eu/data/ury.svg","name":"Uruguay","capital":"Montevideo","region":"Americas"},
{"flag":"https://restcountries.eu/data/uzb.svg","name":"Uzbekistan","capital":"Tashkent","region":"Asia"},
{"flag":"https://restcountries.eu/data/vut.svg","name":"Vanuatu","capital":"Port Vila","region":"Oceania"},
{"flag":"https://restcountries.eu/data/ven.svg","name":"Venezuela (Bolivarian Republic of)","capital":"Caracas","region":"Americas"},
{"flag":"https://restcountries.eu/data/vnm.svg","name":"Viet Nam","capital":"Hanoi","region":"Asia"},
{"flag":"https://restcountries.eu/data/wlf.svg","name":"Wallis and Futuna","capital":"Mata-Utu","region":"Oceania"},
{"flag":"https://restcountries.eu/data/esh.svg","name":"Western Sahara","capital":"El Aaiún","region":"Africa"},
{"flag":"https://restcountries.eu/data/yem.svg","name":"Yemen","capital":"Sana'a","region":"Asia"},
{"flag":"https://restcountries.eu/data/zmb.svg","name":"Zambia","capital":"Lusaka","region":"Africa"},
{"flag":"https://restcountries.eu/data/zwe.svg","name":"Zimbabwe","capital":"Harare","region":"Africa"}]

def getCountryNames(countries):
	regionDictionary = {}

	for country in countries:
		name = country["name"]
		capital = country["capital"]
		region = country["region"]
		flag = country["flag"]

		if region not in regionDictionary:
			regionDictionary[region] = [{name : [capital, flag]}]
		else:
			regionDictionary[region] += [{name : [capital, flag]}]

		

		#t = each["name"].decode('utf8') #.encode('cp1250')
	print regionDictionary



subsetCountries = allCountries = [{"flag":"https://restcountries.eu/data/afg.svg","name":"Afghanistan","capital":"Kabul","region":"Asia"},
{"flag":"https://restcountries.eu/data/ala.svg","name":"Åland Islands","capital":"Mariehamn","region":"Europe"},
{"flag":"https://restcountries.eu/data/alb.svg","name":"Albania","capital":"Tirana","region":"Europe"},
{"flag":"https://restcountries.eu/data/dza.svg","name":"Algeria","capital":"Algiers","region":"Africa"},]
getCountryNames(allCountries)
print "\n\n\n\n\n\n\n\n\nsubset countries:"

getCountryNames(subsetCountries)










